# Generated by Django 4.1.5 on 2023-02-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_newletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newletter',
        ),
    ]
